"""init

Revision ID: 8fd6480c73fe
Revises: 
Create Date: 2026-05-13 17:06:21.649814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd6480c73fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('payload_size_bytes', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('partition_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'partition_key'),
    postgresql_partition_by='RANGE (partition_key)'
    )
    op.create_index('ix_logs_model_id', 'communication_logs', ['model_id'], unique=False)
    op.create_index('ix_logs_timestamp', 'communication_logs', ['timestamp'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('msg', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('partition_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'partition_key'),
    postgresql_partition_by='RANGE (partition_key)'
    )
    op.create_index('ix_metrics_timestamp', 'metrics', ['timestamp'], unique=False)
    op.create_index('ix_metrics_type_name', 'metrics', ['metric_type', 'metric_name'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('long_description', sa.String(), nullable=False),
    sa.Column('params', sa.String(), nullable=False),
    sa.Column('framework', sa.String(), nullable=False),
    sa.Column('license', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('mcp_tool', sa.String(), nullable=False),
    sa.Column('input_types', sa.JSON(), nullable=True),
    sa.Column('output_types', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('use_cases', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('throughput_rps', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_aggregates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_aggregates_timestamp'), 'subscription_aggregates', ['timestamp'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_model_id'), 'subscriptions', ['model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_model_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_subscription_aggregates_timestamp'), table_name='subscription_aggregates')
    op.drop_table('subscription_aggregates')
    op.drop_table('models')
    op.drop_index('ix_metrics_type_name', table_name='metrics')
    op.drop_index('ix_metrics_timestamp', table_name='metrics')
    op.drop_table('metrics')
    op.drop_table('incidents')
    op.drop_index('ix_logs_timestamp', table_name='communication_logs')
    op.drop_index('ix_logs_model_id', table_name='communication_logs')
    op.drop_table('communication_logs')
    # ### end Alembic commands ###
